- project:
    check:
      jobs:
#        - linters:
#            vars:
#              linters:
#                - "ansible-lint"
#                - "yamllint"
#        - "thoth-coala"
        - "thoth-redeploy"

    gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
    post:
      jobs:
        - "trigger-build":
            vars:
              webhook_url: "https://paas.upshift.redhat.com/oapi/v1/namespaces/thoth-test-core/buildconfigs/user-api/webhooks"
    kebechet-auto-gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"

- job:
    name: "thoth-redeploy"
    parent: "base-openshift-pod"
    run: "devops_redeploy.yaml"
    nodeset:
      nodes:
        - name: "pod"
          label: "thoth-ops"

- job:
    name: "push-image"
    parent: "base-openshift-pod"
    run: "devops_push_image.yaml"
    nodeset:
      nodes:
        - name: "pod"
          label: "thoth-ops"

- secret:
    name: thoth_ops_sa
    data:
        api_url: https://paas.upshift.redhat.com:443
        project: thoth-test-core
        token: !encrypted/pkcs1-oaep
        - vzA4YoJ/f5tg2R1BK8m9kxcBs+XxaZAoUaQwtj+cnRigV1cE6sXobA2V+R/XcsXnDrMxq
          DGPt7gR1Mysqfyc5VoPzomeOL58chSstj2qKwl2WXZ6lFQf2pN1/02NPgaaQSwdrPgH2n
          hLdAl0/LyORbC+38P9XpPe2nwZ0iB5d18u4tfx1JME5p6uWv8rA4jxnOEZFYL0XJ0bwlj
          b2KrbLkrxstm3sYRYoXLi/G5bk88b6SpSQM3rqZy5oB8UjKQxE+qyu1Mv0em/c5fnHicH
          T2MDfg78kVZQfkg/9ESFglH5cfYSUKTK9lF5/EiTWeRa+PuEErhqexUCtiLffq2jETUcU
          l2O5yQjp0vJzLclJCfUFi9AtMCFZTezDR7L+xLynVr8CmDyGZoGCn4uFIVr7VXB6hWIfw
          uD4YIY/udaXAbHI5nyQ1Wn++f1UxV6S00+XHU7hhQjAh4ItVgVMbOqgS//dM0Sv8+XWZI
          CzonQXeLMUNw3n04CMXqUH/1L7CxRRgJD3KmXUlxImXtoWBGD2Ku5IqcTm7pThCvFQM5j
          nJHW6lO2ampr8ry1aR5AVjDLKS1yssNYA2cTY7WIZbiD1iJ4yREHndaPrTlwdb3l0RB46
          XxadJtxkHtFe357IFkYbW1wOsakBJZqFpAwKfiVR0CeirxTZxyXcJ/QGM9/jzQ=
        - PvCmKsVtmHB75sbRasXm2eZIW87OrgnXy0KAa7tRSzUDLjeaDGbDKqg3Z6aLr0NawRCXs
          paWe+GPINhwYvaPekh0DuVkqNPQt3kZebaLL/Te67NLL6wTSRrfKZmdgh1JKwrGNUyQcJ
          ZXtVQAcaTaeV9yfXOz6R4wXZ75eVGBQIYRoc0K/KF5SfOWdRO/sxecLcx7uXcC5+hgciT
          pbLQclaykUdxDE9W1g3C4g+VnNSDAoqnNbHU1jf8ZO2TF6mNnZH3I36eZc8k3xozfFuQE
          z0PrmQlDAIW9cDON5jUU1bGQp3QtY3TBHz+wkJJr/DYZO93tWx4TLHJbJWAt6rQ3I6YnJ
          HYHD/jAAtiGfWHcmjx+zJHL0QZXEmGheIgYrfXIEZm55asUL5hzOdQGsWpS6MimTd7Nm/
          wy1TcotRYm9mklyUuKReO2a/TCbzJNdvsxjVjw0ceBnNdRY66ztpVy1PL8+7O+gpYj3x3
          o3f49taQIvYMBiHpOd+8ItykUTVBtMDavdU/ixtpSdSdU4ohRzv/SOnSIumQlEAedBBGw
          BkxBFGhABOw5mmDdJY3FJNu48ggBC65TP6oKd7DJqwkg/ebSIQZXqhPfwdWp+QiZeSIB2
          yofHcO2vWh+MvrU2M+HbIw7wlwzG8HG7U0ZcB6L0VM7JW1Up0jx4GUlZxzrVt0=
