- project:
    check:
      jobs:
        - linters:
            vars:
              linters:
                - "ansible-lint"
                - "yamllint"
        - "thoth-coala"
    gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: "https://paas.upshift.redhat.com/oapi/v1/namespaces/thoth-test-core/buildconfigs/user-api/webhooks"
    kebechet-auto-gate:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"

- job:
    name: "thoth-redeploy"
    parent: "base-openshift-pod"
    run: "devops_redeploy.yaml"
    nodeset: "thoth-ops-pod"

- job:
    name: "push-image"
    parent: "base-openshift-pod"
    run: "devops_push_image.yaml"
    nodeset: "thoth-ops-pod"
