swagger: "2.0"
info:
  title: Thoth user API
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json
paths:
  /analyze:
    post:
      tags: [Management]
      operationId: thoth_user_api.api_v1.api_analyze
      summary: Analyze the given image asynchronously.
      parameters:
        - name: image
          in: query
          required: true
          description: Name of image - can also specify remote registry to pull image from.
          type: string
        - name: analyzer
          in: query
          required: true
          description: Name of analyzer (OpenShift build) to be triggered
          type: string
        - name: debug
          in: query
          required: false
          description: Run the given analyzer in a verbose mode so developers can debug analyzer (requires access to the OpenShift console).
          type: boolean
          default: false
        - name: timeout
          in: query
          required: false
          description: Give a timeout to commands run inside the analyzer container.
          type: integer
        - name: cpu-request
          in: query
          required: false
          description: CPU request for the analyzer run
          type: string
        - name: memory-request
          in: query
          required: false
          description: Memory request for the analyzer run
          type: string
      responses:
        202:
          description: Successful response.
        400:
          description: On invalid request.

  /parse-log:
    post:
      tags: [Utils]
      operationId: thoth_user_api.api_v1.api_parse_log
      summary: Parse Docker build log or installation log and show installed packages.
      parameters:
        - name: log_info
          in: body
          required: true
          description: A full log.
          schema:
            $ref: "#/definitions/Log"
      responses:
        200:
          description: Successful response.
        400:
          description: On invalid request.

  /pod-log:
    get:
      tags: [Management]
      operationId: thoth_user_api.api_v1.api_pod_log
      summary: Show logs of requested analyzes.
      parameters:
        - name: pod_id
          in: query
          required: true
          description: An ID of requested analyzis.
          type: string
      responses:
        200:
          description: Successful response.
        400:
          description: On invalid request.

definitions:
  Log:
    type: object
    required:
      - 'log'
    additionalProperties: false
    properties:
      log:
        type: string
        description: A full build or installation log that was output during image build.
        example: >
          Collecting tensorflow
            Downloading tensorflow-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (41.2MB)
          Successfully installed tensorflow-1.4.1
