apiVersion: v1
kind: Template
labels:
  template: thoth-user-api-buildconfig
  thoth: 0.1.0
metadata:
  name: thoth-user-api-buildconfig
  annotations:
    description: This is Thoth User API BuildConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    openshift.io/display-name: Thoth User API BuildConfig
    version: 0.1.1
    tags: poc,thoth,thoth-user-api,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This is Thoth User API BuildConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
#
# Image streams
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: thoth-core
    name: user-api
  spec:
    name: stable

#
# Build configs
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: user-api
    labels:
      app: thoth-core
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "user-api:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: ${GITHUB_URL}
        ref: ${GITHUB_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
    triggers:
    - type: ImageChange
      imageChange: {}

parameters:
- description: Name of the github repository for Thoth's User API
  displayName: Git Repository
  required: true
  name: GITHUB_URL
  value: 'https://github.com/thoth-station/user-api'

- description: Git reference to be used for Thoth's User API
  displayName: Git Reference
  required: true
  name: GITHUB_REF
  value: 'master'

- description: Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'